# This file was generated by GoReleaser. DO NOT EDIT.
cask "grits" do
  version "0.1.15"

  on_macos do
    on_intel do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_darwin_amd64.tar.gz"
      sha256 "81e44beefdb88df342e773b7c06465f156c6422e7b5c14e69b0e9b3574c2095b"
    end
    on_arm do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_darwin_arm64.tar.gz"
      sha256 "cfbcad4ee7edc86e774745e5394d0d1fe1f308980133e3b8d2fe356f781e470d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_linux_amd64.tar.gz"
      sha256 "33f37d8085fffecb99b2344601bf9e2430cbfce9b8f5c7213fcdf6e9f0926331"
    end
    on_arm do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_linux_arm64.tar.gz"
      sha256 "9e5d42682422dea338809e6da0859803b2f4fc22b6433a2fc1cfc00b1fdd0c2c"
    end
  end

  name "grits"
  desc "CLI & MCP Server for Grits — Agentic PM & OKR platform"
  homepage "https://github.com/gritive/grits-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grits"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grits"]
    end
  end

  # No zap stanza required

end
