# This file was generated by GoReleaser. DO NOT EDIT.
cask "grits-journal" do
  version "0.1.12"

  on_macos do
    on_intel do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_darwin_amd64.tar.gz"
      sha256 "b9c8b740e31e70d14f506944f179dc3f20d464db1e78af74748ade662c033120"
    end
    on_arm do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_darwin_arm64.tar.gz"
      sha256 "7ec906fad2b48780ee36318d84612b26cf8544a4b97d1ec1530311d84d430deb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_linux_amd64.tar.gz"
      sha256 "6a60d57cf90808b668f72ee194fcf83461ee238e001a6038df2405109e0a94ae"
    end
    on_arm do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_linux_arm64.tar.gz"
      sha256 "33d3f953a5cd2d742af519cc4689555727445b06d2aaf1498f65b16ba260f1ec"
    end
  end

  name "grits-journal"
  desc "Local work journal for AI coding agents — zero signup, zero server"
  homepage "https://github.com/gritive/grits"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grits-journal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grits-journal"]
    end
  end

  # No zap stanza required

end
