# This file was generated by GoReleaser. DO NOT EDIT.
cask "grits-journal" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "3a449d1439bf2ae6e79e9d242b1115f2b8f841d07c563ea34d44f243cee6bf3e"
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f33e486b67354ad6579142be8ceed6671d0dd25c7dafaa11be713119d15bded"
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9de53c735cf269b437dc44fb35775340e8c6bda77d9ac7ac3ab10c105f7442c"
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ec0b04e645e91b82fd6f9fb889a75dbe8bfaff9c9790b678e27071fb00026be"
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "grits-journal"
  desc "Local work journal for AI coding agents — zero signup, zero server"
  homepage "https://github.com/gritive/grits"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grits-journal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grits-journal"]
    end
  end

  # No zap stanza required

end
