# This file was generated by GoReleaser. DO NOT EDIT.
cask "grits" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "3f81b0bbf10a62d19d67cb2991cfe2f87e4ce5176c57f29c6614cc1428cc1844"
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5279f9cdf2b5b8dba20e02f28cac3e89eaccd57350ba9332e69cda1d6847d979"
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b188fdec5a1025e20cf7efa3a167d629995c724508b3e571d6945a41076f9694"
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a0a84048c024dcd1ba9ad3db0e3f0b6edb25b30db8c0e5e4e16c2a8c1c5b12b"
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_linux_arm64.tar.gz"
    end
  end

  name "grits"
  desc "CLI & MCP Server for Grits — Agentic PM & OKR platform"
  homepage "https://github.com/gritive/grits-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grits"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grits"]
    end
  end

  # No zap stanza required

end
