# This file was generated by GoReleaser. DO NOT EDIT.
cask "grits" do
  name "grits"
  desc "CLI & MCP Server for Grits — Agentic PM & OKR platform"
  homepage "https://github.com/gritive/grits-agent"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grits"

  on_macos do
    on_intel do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_darwin_amd64.tar.gz"
      sha256 "85336195ab12f7d9852a452f97de48d80a043d9333a17d249ca24833292aaf42"
    end
    on_arm do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_darwin_arm64.tar.gz"
      sha256 "c9592716928f5895093d74d2ed146572008bc12e9acdb394ed5b38c08d3fb5cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_linux_amd64.tar.gz"
      sha256 "2d901069ca7ffb0a72090ca4365fa86c17dc470c0d4815453dfe8430721bc9ae"
    end
    on_arm do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits_#{version}_linux_arm64.tar.gz"
      sha256 "ec2432375812136a390227af348959b745a3f9af066a19883e4d350e3b40981a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grits"]
    end
  end

  # No zap stanza required
end
