# This file was generated by GoReleaser. DO NOT EDIT.
cask "grits-journal" do
  version "0.1.15"

  on_macos do
    on_intel do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_darwin_amd64.tar.gz"
      sha256 "34f1177d9f3b6d9c666570eeec7f1cf317bea5323afa05a20185b4bb3e0bf425"
    end
    on_arm do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_darwin_arm64.tar.gz"
      sha256 "7fb59e09e254651df57694e9c9bafd4e1ab35ac34a265f897f8c90f0171d5962"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_linux_amd64.tar.gz"
      sha256 "6174567653b9943c92bf14f92c386b9c4d758455746e5ad6db269e24dd9596bf"
    end
    on_arm do
      url "https://github.com/gritive/grits-agent/releases/download/v#{version}/grits-journal_#{version}_linux_arm64.tar.gz"
      sha256 "df1155ffd19859208c2f7772dc711455c85c246e328562194783411d7a636d8c"
    end
  end

  name "grits-journal"
  desc "Local work journal for AI coding agents — zero signup, zero server"
  homepage "https://github.com/gritive/grits"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grits-journal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grits-journal"]
    end
  end

  # No zap stanza required

end
